name: BudgetTrackerDeploy

on:
  push:
    branches: ['master']

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependancies
        run: npm ci

      - name: Build Angular PWA App
        run: npm build --configuration=production --base-href=/budgetTrackerAngular/

      - name: Deploy to Github Pages
        uses: peaceiris/action-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          publish_dir: ./dist/budget-tracker/browser
