name: BudgetTrackerDeploy

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  
  workflow_dispatch:

    jobs:
      build-deploy:
        runs-on: ubuntu-lastest
        steps:
          - uses: actions/checkout@v4

          - name: Setup Node
            uses: actions/setup-node@v4
            with:
              node-version: 22

          - name: Install Dependancies
            run: npm ci

          - name: Build Angular PWA App
            run: npm build --configuration:production

          - name: Deploy to Github Pages
            uses: peaceiris/actions-gh-pages@v4
            with: 
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./dist/budget-tracker/browser

